apiVersion: v1
kind: Service
metadata:
  name: {{ include "scaleway-billing-collector.fullname" . }}
  labels:
    {{- include "scaleway-billing-collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "scaleway-billing-collector.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
