{
 "title": "Scaleway realtime costs",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_name",
    "label": "Project name",
    "query": {
     "query": "label_values(scaleway_billing_cost_euros_total,project_name)"
    }
   },
   {
    "name": "category_name",
    "label": "Category",
    "query": {
     "query": "label_values(scaleway_billing_cost_euros_total{project_name=~\"${project_name:regex}\"},category_name)"
    }
   },
   {
    "name": "product_name",
    "label": "Product name",
    "query": {
     "query": "label_values(scaleway_billing_cost_euros_total{project_name=~\"${project_name:regex}\",category_name=~\"${category_name:regex}\"},product_name)"
    }
   },
   { "name": "burn_rate", "label": "Burn-rate filter" }
  ]
 },
 "panels": [
  {
   "title": "Resource usage cost from ${__from:date:HH:mm:ss} to ${__to:date:HH:mm:ss}",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  sum(increase(scaleway_billing_cost_euros_total{\n    project_name=~\"${project_name:regex}\",\n    category_name=~\"${category_name:regex}\",\n    product_name=~\"${product_name:regex}\",\n    unit!~\"EUR|plan|currency\",\n    billing_line_type=\"resource_usage\",\n    burn_rate_eligible=~\"${burn_rate:raw}\"\n  }[$__range]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource usage cost by product from ${__from:date:HH:mm:ss} to ${__to:date:HH:mm:ss}",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (project_name, category_name, product_name, resource_name, sku, unit, billing_usage_type, burn_rate_eligible) (\n  increase(scaleway_billing_cost_euros_total{\n    project_name=~\"${project_name:regex}\",\n    category_name=~\"${category_name:regex}\",\n    product_name=~\"${product_name:regex}\",\n    unit!~\"EUR|plan|currency\",\n    billing_line_type=\"resource_usage\",\n    burn_rate_eligible=~\"${burn_rate:raw}\"\n  }[$__range])\n) > 0",
     "legendFormat": "{{project_name}} / {{category_name}} / {{product_name}} / {{resource_name}} / {{unit}}"
    }
   ]
  },
  {
   "title": "Hourly resource usage cost from ${__from:date:HH:mm:ss} to ${__to:date:HH:mm:ss}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "sum by (project_name, category_name, product_name, resource_name, unit, billing_usage_type, burn_rate_eligible) (\n  increase(scaleway_billing_cost_euros_total{\n    project_name=~\"${project_name:regex}\",\n    category_name=~\"${category_name:regex}\",\n    product_name=~\"${product_name:regex}\",\n    unit!~\"EUR|plan|currency\",\n    billing_line_type=\"resource_usage\",\n    burn_rate_eligible=~\"${burn_rate:raw}\"\n  }[1h])\n) > 0",
     "legendFormat": "{{project_name}} / {{category_name}} / {{product_name}} / {{resource_name}} / {{unit}}"
    }
   ]
  }
 ]
}